### PR TITLE
fix(config): update jsDelivrHitsEndpoint url

### PR DESCRIPTION
**Pull request by MartinKolarik**
Following up on #1074 and switching the URL to our prod env.

### CODE REVIEW

**Comment by Haroenv** [comment]
Looks like something went wrong with CI, I'm not sure if it will build, but I'll try to fix it

**Comment by MartinKolarik** [comment]
Can you confirm if/when this is live? In our APM, I'm seeing only requests coming from version 1.7.7, which is quite old 🤔 no signs of either 1.7.15. or 1.7.14.

**Comment by Haroenv** [comment]
hm, maybe something didn't work in the release script. I'm seeing a failure with docker

**Comment by MartinKolarik** [comment]
Any idea when you might be able to fix it and deploy the latest version? Since we thought the previous changes were live, we've already deployed our API changes and the URI used here to get package stats no longer works.

**Pull request merged**
