### PR TITLE
feat(typo): promote popular results to avoid typo squatting

### PR DESCRIPTION
**Pull request by Haroenv**
boostrap -> bootstrap

cc @julienbourdeau

### CODE REVIEW

**Comment by Haroenv** [comment]
It works really well, I tried it in testing and in prod (will be overridden soon). 

query I found a bit tough is https://yarn.pm/ract

**Comment by vvo** [comment]
Any concrete examples on the fact that it works really well? Would help understanding this.

Doesn't it have also drawbacks like searching for a particular package name won't show up because we first show the popular ones?

What if I am really searching for ract, will I find it?

**Comment by Haroenv** [comment]
It works well for for example boostrap, which still shows up a few results lower, but bootstrap goes first. Typos very close to react are a bit of an issue because that exact result will only show up at page 10 or so because there are so many popular react packages. Ract was the only example I found here which was hard to find. Others with this issue don’t really exist. You can try this PR out by changing it in production, and it will revert to the real version in a few hours

**Comment by vvo** [comment]
What I would do if feasible if query is `boostrap` is something like:

```
Results
---
2/ Exact match: Boostrap
1/ Most popular match with typo: Bootstrap
3+/ Other results
```

Knowing that in most cases, 1 and 2 would be the same record.
The tricky part of package search is knowing exactly how results are ranked. If I can ALWAYS rely on the fact that the top result is either a typo (google like "did you mean?") OR the exact match, that's better.

Otherwise if my exact match is always either 3rd, 4th, 5th without easy to understand rule that's hard. That's how npm search became tricky to understand to me. By trying to be smart, on 400000+ packages, it ended up being complex to understand the results and rely on them (= sometime I would find ract, sometime not = frustration and fear of using this search or relying on it).

**Comment by julienbourdeau** [comment]
`react` makes it really hard :/ It seems like in the top 1% we want to boost, half of it will be related to react. I'm not sure what to do.

**Comment by Haroenv** [comment]
I wonder how we could solve this

**Comment by Haroenv** [comment]
This has negative aspects which make it too hard to find packages which are very close to popular one. Closing for that reason

**Pull request closed without merging**
