### PR TITLE
feat(keywords): add webpack-scaffold

### PR DESCRIPTION
**Pull request by evenstensberg**
Adds webpack scaffold to lookup :)

### CODE REVIEW

**Comment by Haroenv** [comment]
Thanks for adding this so swiftly!

Two questions: 

- Are you sure you want to enforce the keyword?
- Can you add a small test in the style of the other computed keywords?

**Comment by evenstensberg** [comment]
Like dat 👍

**Comment by evenstensberg** [comment]
Tests were failing locally fwiv, not related to my changes

**Comment by Haroenv** [comment]
Yes, I fixed that on master, thanks for contributing!

This change will be live in about a week (unless you want it earlier, but it will still take at least 24hr)

**Comment by Haroenv** [comment]
I’ll let you know when it’s done. In the mean time, any package that matches and is updated since now will already be filterable

**Comment by evenstensberg** [comment]
Gotcha!

**Pull request merged**
