### PR TITLE
Tweak the searchableAttributes settings to consider popularName first.

### PR DESCRIPTION
**Pull request by redox**
This will require a full re-indexing :)

### CODE REVIEW

**Comment by vvo** [comment]
Do you have an example bad query that will be good afterwards?

**Comment by vvo** [comment]
> This will require a full re-indexing :)

IZY!

**Comment by redox** [comment]
> Do you have an example bad query that will be good afterwards?

Yes, `asyc` for instance.

**Comment by vvo** [comment]
deploying and doing full reindex

**Comment by vvo** [comment]
Was done but result is maybe not what we want:

https://yarnpkg.com/search?q=asyc&p=0&is_v=1

2017-01-03-103911_1380x958_scrot

**Comment by redox** [comment]
Yes, I spot that; I need to iterate on the ranking formula now.

**Pull request merged**
