### PR TITLE
feat: add nsp score

### PR DESCRIPTION
**Pull request by Haroenv**
this pr is just opened to be sure it's mergeable

### CODE REVIEW

**Comment by vvo** [comment]
Any idea on the impact on indexing time?

**Comment by Haroenv** [comment]
pretty significant, but my computer isn't Heroku so it's hard to estimate 🤔

**Comment by vvo** [comment]
Is the nsp team aware of this and OK that we are gonna throw 500 000 requests at them soon?

**Comment by Haroenv** [comment]
Talked to @vdeturckheim about this yesterday. Apparently there are only 250 vulnerabilities in nsp 🤯 The new source of truth is https://github.com/nodejs/security-wg/tree/master/vuln/npm, so we should either clone or get the data in another way instead :) Closing this and will re-work in the future.

**Pull request closed without merging**
