### PR TITLE
feat(deps) add dependencies

### PR DESCRIPTION
**Pull request by Haroenv**
easier than dependents because this is only one level deep.

### CODE REVIEW

**Comment by redox** [comment]
Should we add `devDependencies` as well?

**Comment by Haroenv** [comment]
We could in just the same way, but it's way less relevant for reusers of a package

**Comment by redox** [comment]
> We could in just the same way, but it's way less relevant for reusers of a package

Sure, I think we rather need the opposite. If we now that a package X is always used as a dev dependencies; we'll be able to display `yarn add ... --dev` instead of `yarn add ....`.

**Comment by Haroenv** [comment]
That’s true @redox, but would be more relevant for adding `devDependents` (but that’s in #21)

**Pull request merged**
